### ISSUE TITLE
Python implementation

### ISSUE THREAD

**Issue by ghost** [patel-nikhil/SHCLiveStatReader#2] opened 2020-02-15 08:45 UTC
Just FYI, I rewrote your implementation in Python:
https://github.com/void4/PySHCLiveReader
:)

A question:
Are the memory addresses specific to a certain Stronghold Crusader Extreme version? I'm using V1.2.1-E and the addresses seem to be different (P1 Gold is at 0x122c760 for example). Which version do you use? Are at least the distances between addresses the same between versions?

**Comment by patel-nikhil** [comment] 2020-02-15 17:48
That's awesome! I'll check it out :)

I've been using Stronghold Crusader Extreme, v1.41 - the addresses may be different with different versions, I haven't tried any other versions as of yet.

My thoughts are that the distances between addresses should be the same, as usually objects are stored in contiguous blocks of memory and I see no reason for that to have changed. But I haven't tested and so unfortunately can't confirm.

My suggestion would be to start with stats such as P1 Gold and P1 Population - you mention they are different in v1.1.2-E - then make note of the offset between P1 Gold and P1 Population and you should be able to use that to find P2 Population from P2 Gold etc.

**Comment by ghost** [comment] 2020-02-15 19:25
I have/am working on V1.2 and V1.2.1E. You are right, many of the distances are the same :)

It would be great if we created a crowd-sourced spreadsheet, perhaps @GRhin can share his Google Docs one with us, allowing us to edit it as well. We could have a new tab for every Stronghold Crusader version.

**Comment by GRhin** [comment] 2020-02-16 00:18
The problem is formatting - it can become very cumbersome very quickly if values are thrown in randomly, then it hard to find what you are looking for so it's easier to search again, and the spreadsheet becomes useless. At least that's my fear right now.
We need to find what each area of memory is for ( e.g current stats player 1, or leaderboards, or after-game greatest lord,  etc.) And format a spreadsheet around that.
Also the second page of the spreadsheet is the decimal representation of the address which is used to calculate based on offsets, then is converted back into hex for the front page.

**Comment by GRhin** [comment] 2020-02-18 02:14
Im going to close this. Just like to keep # of issues down, and i dont think theres anything more to discuss here.

**Closed as completed by GRhin** 2020-02-18 02:14 UTC
